# Generated by Django 4.1.6 on 2023-03-24 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('dob', models.IntegerField(max_length=200, null=True)),
                ('age', models.IntegerField(max_length=200, null=True)),
                ('gender', models.CharField(max_length=200, null=True)),
                ('address', models.CharField(max_length=200, null=True)),
                ('phone', models.IntegerField(max_length=200, null=True)),
                ('email', models.CharField(max_length=200, null=True)),
                ('district', models.CharField(max_length=200, null=True)),
                ('account', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
